"""migracao inicial

Revision ID: 9dac662f1b30
Revises: 
Create Date: 2026-04-15 22:17:48.377526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9dac662f1b30'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Jogador',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user', sa.String(length=100), nullable=False),
    sa.Column('nome', sa.String(length=250), nullable=False),
    sa.Column('idade', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('altura', mysql.DECIMAL(unsigned=True, precision=3, scale=2), nullable=False),
    sa.Column('pontos', mysql.SMALLINT(unsigned=True), nullable=False),
    sa.Column('assistencias', mysql.SMALLINT(unsigned=True), nullable=False),
    sa.Column('rebotes', mysql.SMALLINT(unsigned=True), nullable=False),
    sa.Column('roubos', mysql.SMALLINT(unsigned=True), nullable=False),
    sa.Column('bloqueios', mysql.SMALLINT(unsigned=True), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('jogos', mysql.SMALLINT(unsigned=True), nullable=False),
    sa.Column('overall', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('posicao_preferida', sa.Enum('armador', 'ala_armador', 'ala', 'ala_pivo', 'pivo', 'nao_sei', name='posicao'), nullable=False),
    sa.Column('senha', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user')
    )
    op.create_table('Time',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Competicao',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('local', sa.String(length=300), nullable=False),
    sa.Column('status', sa.Enum('em_aberto', 'cancelado', 'confirmado', 'encerrado', name='statuscomp'), nullable=False),
    sa.Column('visibilidade', sa.Enum('publico', 'privado', name='visibilidade'), nullable=False),
    sa.Column('qtd_times', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('tipo', sa.Enum('torneio', 'partida', name='tipocompeticao'), nullable=False),
    sa.Column('fk_Jogador_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('qtd_max_jogadores', mysql.TINYINT(unsigned=True), nullable=False),
    sa.ForeignKeyConstraint(['fk_Jogador_id'], ['Jogador.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Formacao_Time',
    sa.Column('fk_Jogador_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('fk_Competicao_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('fk_Time_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.ForeignKeyConstraint(['fk_Competicao_id'], ['Competicao.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fk_Jogador_id'], ['Jogador.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fk_Time_id'], ['Time.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fk_Jogador_id', 'fk_Competicao_id')
    )
    op.create_table('Jogo',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('resultado', sa.Enum('time_1', 'time_2', name='resultadojogo'), nullable=True),
    sa.Column('pontuacao_2', mysql.TINYINT(unsigned=True), nullable=True),
    sa.Column('pontuacao_1', mysql.TINYINT(unsigned=True), nullable=True),
    sa.Column('fk_Competicao_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('horario', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['fk_Competicao_id'], ['Competicao.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Participacao',
    sa.Column('fk_Jogador_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('fk_Competicao_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('resposta', sa.Enum('confirmado', 'recusado', 'esperando_retorno', name='respostaparticipacao'), nullable=True),
    sa.ForeignKeyConstraint(['fk_Competicao_id'], ['Competicao.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fk_Jogador_id'], ['Jogador.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('fk_Jogador_id', 'fk_Competicao_id')
    )
    op.create_table('Partida',
    sa.Column('fk_Competicao_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('horario', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['fk_Competicao_id'], ['Competicao.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fk_Competicao_id')
    )
    op.create_table('Torneio',
    sa.Column('fk_Competicao_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('data_inscricoes', sa.Date(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['fk_Competicao_id'], ['Competicao.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fk_Competicao_id')
    )
    op.create_table('Classificacao',
    sa.Column('fk_Time_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('fk_Torneio_fk_Competicao_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('classificacao', mysql.TINYINT(unsigned=True), nullable=False),
    sa.ForeignKeyConstraint(['fk_Time_id'], ['Time.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fk_Torneio_fk_Competicao_id'], ['Torneio.fk_Competicao_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('fk_Time_id', 'fk_Torneio_fk_Competicao_id')
    )
    op.create_table('Estatistica',
    sa.Column('fk_Jogador_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('fk_Jogo_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('fk_Time_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('roubos', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('rebotes', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('assistencias', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('bloqueios', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('pontos', mysql.TINYINT(unsigned=True), nullable=False),
    sa.ForeignKeyConstraint(['fk_Jogador_id'], ['Jogador.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fk_Jogo_id'], ['Jogo.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fk_Time_id'], ['Time.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('fk_Jogador_id', 'fk_Jogo_id')
    )
    op.create_table('Time_Jogo',
    sa.Column('fk_Time_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('fk_Jogo_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('resultado', sa.Enum('vitoria', 'derrota', 'empate', name='resultadotimejogo'), nullable=True),
    sa.Column('pontuacao_total', mysql.TINYINT(unsigned=True), nullable=False),
    sa.ForeignKeyConstraint(['fk_Jogo_id'], ['Jogo.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fk_Time_id'], ['Time.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('fk_Time_id', 'fk_Jogo_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Time_Jogo')
    op.drop_table('Estatistica')
    op.drop_table('Classificacao')
    op.drop_table('Torneio')
    op.drop_table('Partida')
    op.drop_table('Participacao')
    op.drop_table('Jogo')
    op.drop_table('Formacao_Time')
    op.drop_table('Competicao')
    op.drop_table('Time')
    op.drop_table('Jogador')
    # ### end Alembic commands ###
